runtime: go111

handlers:
- url: /js
  static_dir: js
  secure: always
- url: /images
  static_dir: images
  secure: always
- url: /worker
  script: auto
  secure: optional
- url: /.*
  script: auto
  login: required
  secure: always
env_variables:
  BOOTSTRAP_USER: 'frederic.app.test@gmail.com'
